routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get("/KC-admin/2ýžhs7429sj28sjsaí2", "SystemController@migrate")->name("migrate");
Route::get("/KC-admin/7aUaoe0pyAsds29apa", "SystemController@rollback")->name("rollback");
Route::get("/privacypolicy", "SystemController@privacypolicy")->name("privacypolicy");

//FRONT END
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::get("/product/{id}/{slug?}", "ProductsController@show")->name("showProduct");

//Cart stuff
Route::get("/cart", "CartController@index")->name("cart.index");
Route::post("/cart/{id}", "CartController@store")->name("cart.store");
Route::delete("/cart/{product}", "CartController@destroy")->name("cart.destroy");
Route::post("/cart/update/chngqty", "CartController@update")->name("cart.changeqty");
Route::post("/cart/update/chngsize", "CartController@updateSize")->name("cart.changesize");

//USER INTERFACE
Route::get("/user/settings", "UsersController@index")->name("users.index");
Route::put("/user/settings/{id}", "UsersController@update")->name("users.update");
Route::get("/user/settings/changeavatardefault/{id}", "UsersController@changeToDefault")->name("users.changeToDefault");
Route::get("/user/settings/password", "UsersController@pass")->name("users.pass");
Route::put("/user/settings/password/{id}", "UsersController@updatePass")->name("users.updatePass");
Route::get("/user/settings/shipping", "UsersController@shipping")->name("users.shipping");
Route::put("/user/settings/shipping/{id}", "UsersController@updateShipping")->name("users.updateShipping");
Route::post("/user/settings/shipping/{id}", "UsersController@storeShipping")->name("users.storeShipping");
Route::get("/user/orders", "UsersController@orders")->name("users.orders");
Route::get("/user/orders/{id}/faktura", "OrdersController@invoice")->name("orders.invoice");
Route::delete("/user/orders/{id}/delete", "OrdersController@order")->name("orders.delete");

//PAYMENTS
Route::post("/create-payment", "PaymentController@create");
Route::post("/execute-payment", "PaymentController@execute");
Route::post("/paymentsuccess", "PaymentController@success");
Route::get("/thankyou", "PaymentController@thankyou")->name("thankyou");

//Checkout stuff
Route::get("/checkout", "CheckoutController@index")->name("checkout.index");
Route::post("/checkout", "CheckoutController@store")->name("checkout.store");


//API AJAX CALLS
Route::get("/getcart", "ProductsController@getCart");

//Products by collection
Route::get("/collections/{slug}", "CollectionsController@show")->name("showCollection");
Route::post("/collectionclick", "CollectionsController@click")->name("collectionclick");

Route::get("/categories/{slug}", "SectionsController@show")->name("homesections.show");

//Search for products
Route::get("/search", "ProductsController@search")->name("searchProducts");
Route::get("/searchfilter", "ProductsController@filter")->name("products.filterSearch");
Route::get("/clearsearch", "ProductsController@emptySearch")->name("products.clearSearch");
Route::post("/rate", "ProductsController@rate");


//BACK END
Route::get("/KC-admin", "AdminController@index")->name("admin.index");
Route::get("/KC-admin/dashboard", "AdminController@index")->name("admin.index");
Route::get("/KC-admin/login", "AdminController@login")->name("admin.login");

// Admin users
Route::get("/KC-admin/user/customers", "AdminUsersController@customers")->name("admin.users.clients");
Route::get("/KC-admin/user/employees", "AdminUsersController@employees")->name("admin.users.employees");
Route::get("/KC-admin/user/users", "AdminUsersController@users")->name("admin.users.user");
//User edit page in admin
Route::get("/KC-admin/user/{id}/edit", "AdminUsersController@edit")->name("admin.users.edit");
Route::put("/KC-admin/user/{id}", "AdminUsersController@update")->name("admin.users.update");
Route::delete("/KC-admin/user/{id}", "AdminUsersController@destroy")->name("admin.users.destroy");

Route::get("/KC-admin/orders", "AdminOrdersController@index")->name("admin.orders.index");
Route::get("/KC-admin/orders/{id}", "AdminOrdersController@edit")->name("admin.orders.edit");
Route::put("/KC-admin/orders/{id}", "AdminOrdersController@update")->name("admin.orders.update");
Route::put("/KC-admin/orders/{id}/products", "AdminOrdersController@updateProducts")->name("admin.orders.updateProducts");
Route::get("/KC-admin/orders/{id}/finish", "AdminOrdersController@finish")->name("admin.orders.finish");
Route::delete("/KC-admin/orders/{id}", "AdminOrdersController@destroy")->name("admin.orders.destroy");

// Admin products
Route::delete("/KC-admin/products/destroyImages", "AdminProductsController@destroyMultipleImages");
Route::delete("/KC-admin/products/destroyImg/image/{id}", "AdminProductsController@destroyImg")
	->name("destroyImg");
Route::resource("/KC-admin/products", "AdminProductsController", [
	"except" => "show"
]);

//API AJAX CALLS
Route::post("/addtofavorites", "ProductsController@addProductToFavorites")->name("products.addToFavorites");
Route::get("/loadmoreproducts/{offset}", "HomeController@loadmoreproducts");
Route::get("/getfavorites", "ProductsController@getFavorites");
Route::get("/getlastvisited", "ProductsController@getLastVisited");
Route::post("/addtorecommended", "ProductsController@addToRecommended");
Route::get("/getrecommendedproducts", "ProductsController@getRecommended");

//AJAX Search
Route::get("/ajax-search", "ProductsController@ajaxsearch");
Route::get("/filter-products", "SectionsController@filter")->name("products.filter");
Route::get("/filter-collection-products", "CollectionsController@filter")->name("products.filterCollections");

//Update formuláře
Route::put("/KC-admin/products/{id}/updateTags", "AdminProductsController@updateTags")->name("products.updateTags");
Route::put("/KC-admin/products/{id}/updatePhotos", "AdminProductsController@updatePhotos")->name("products.updatePhotos");
Route::put("/KC-admin/products/{id}/updateQuantities", "AdminProductsController@updateQuantities")->name("products.updateQuantities");
Route::put("/KC-admin/products/{id}/updateColors", "AdminProductsController@updateColors")->name("products.updateColors");
Route::post("/KC-admin/products/storeSku", "AdminProductsController@storeSku")->name("products.storeSku");

Route::post("/KC-admin/products/ajax-upload/{productId}", "AdminProductsController@ajaxImgUpload")
	->name("product-ajax-upload");
Route::post("/KC-admin/products/uploadMoreImages", "AdminProductsController@uploadMultipleImages")
	->name("uploadMoreImages");
Route::post("/KC-admin/products/updateImgPosition", "AdminProductsController@updatePhotosPosition");
Route::post("/KC-admin/products/updateSlidesPosition", "AdminSlidersController@updateSlidesPosition");


// Admin sliders
Route::resource("/KC-admin/sliders", "AdminSlidersController", [
	"except" => "show"
]);
Route::post("/click", "SlidersController@click");
Route::put("/KC-admin/sliders/{id}/changeActive", "AdminSlidersController@changeActive")->name("sliders.changeActive");

// Admin collections
Route::resource("/KC-admin/collections", "AdminCollectionsController", [
	"except" => "show"
]);

// Admin sections
Route::resource("/KC-admin/sections", "AdminSectionsController");

// Admin tags
Route::resource("/KC-admin/tags", "AdminTagsController", [
	"except" => "show"
]);

Route::get('adminauth/google', 'SocialAuthController@redirectToAdminProvider');

Route::get('auth/{provider}', 'SocialAuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'SocialAuthController@handleProviderCallback');

resources/views/home.blade.php
@extends('layouts.app')

@section("title", "Home")

@section('content')
	<div class="container-full">
		<div class="click-left"></div>
		<div class="click-right"></div>
		<div class="hp-slider slider" id="hp-slider">
			@foreach($slides as $slide)
				<div data-id="{{ $slide->id }}"
				     data-redirect="@if($slide->hasDestination()){{ url("/") . $slide->url_dest }} @endif"
				     class="slide clickable">
					<div class="slide-darken"></div>
					<div class="img-slide">
						<img src="{{ $slide->getCoverImg() }}" alt="slide background">
					</div>
					<div class="container">
						<h2>{{ $slide->heading }}</h2>
						<p>{{ $slide->text }}</p>
					</div>
				</div>
			@endforeach
		</div>
	</div>

	<div class="section">
		<div class="container">
			<h2>Newest products</h2>
			<div class="row products-row">
				@foreach($newestProducts as $product)
					<div class="col-6 col-sm-4 col-md-3">
						<div class="product-box">
							<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}">
								<div class="product-head">
									<img src="{{ asset($product->getCoverImgMin()) }}" alt="Product image">
									@if($product->hasSku())
										<div class="variations">
											{{ $product->children()->count() + 1 }} variations
										</div>
									@endif
								</div>
							</a>
							<div class="product-body">
								<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}">
									<p>{{ $product->name }}</p></a>
								<span>{{ $product->presentPrice() }} DOLLARS</span>
							</div>
						</div>
					</div>
				@endforeach
			</div>
			<div class="content faded-sm-text">
				<p>
					<a class="load-more-button" href="">
						Load more
						<span class="plus"></span>
					</a>
				</p>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="container">
			<div class="collection-container">
				<div class="row">
					@foreach($collections as $collection)
						<div class="col-12 col-sm-6 col-md-4">
							<a data-id="{{ $collection->id }}" class="click-count"
							   data-call="{{ route("collectionclick") }}"
							   href="{{ route("showCollection", $collection->slug) }}">
								<div class="collection-box">
									<div title="{{ $collection->name }}" class="absolute-box">
										<p>{{ $collection->name }}</p>
									</div>
									<img src="{{ $collection->getImg() }}" alt="Collection image">
								</div>
							</a>
						</div>
					@endforeach
				</div>
			</div>
		</div>
	</div>

	<div class="section slider-section">
		<div class="container">
			<h2>Hottest products</h2>
			<div class="slider-products hottest-products">
				@foreach($hottestProducts as $product)
					<div class="product-box">
						<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}">
							<div class="product-head">
								<img src="{{ asset($product->getCoverImgMin()) }}" alt="Product image">
							</div>
						</a>
						<div class="product-body">
							<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}">
								<p>{{ $product->name }}</p></a>
							<span>{{ $product->presentPrice() }} DOLLARS</span>
						</div>
					</div>
				@endforeach
			</div>
		</div>
	</div>

	<div class="section slider-section pt-4">
		<div class="container recommend-container">
			<h2>Products you might like</h2>
			<div class="recommended-slider slider-products">
				<div class="product-box placeholder mr-2 float-left">
					<div class="product-head"></div>
					<div class="product-body">
						<div class="name"></div>
						<div class="price"></div>
					</div>
				</div>
				<div class="product-box placeholder mr-2 float-left">
					<div class="product-head"></div>
					<div class="product-body">
						<div class="name"></div>
						<div class="price"></div>
					</div>
				</div>
				<div class="product-box placeholder mr-2 float-left">
					<div class="product-head"></div>
					<div class="product-body">
						<div class="name"></div>
						<div class="price"></div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/privacypolicy.blade.php
@extends("layouts.app")

@section("content")
	<style>
		.iubenda-ibadge {
			display: block;
			margin: 20px auto 0 auto;
		}
	</style>
	<div class="col-12">
		<a href="https://www.iubenda.com/privacy-policy/32365074" class="iubenda-white iubenda-embed text-center mt-4"
		   title="Privacy Policy ">Privacy Policy</a>
		<script type="text/javascript">(function (w, d) {
				var loader = function () {
					var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0];
					s.src = "https://cdn.iubenda.com/iubenda.js";
					tag.parentNode.insertBefore(s, tag);
				};
				if (w.addEventListener) {
					w.addEventListener("load", loader, false);
				} else if (w.attachEvent) {
					w.attachEvent("onload", loader);
				} else {
					w.onload = loader;
				}
			})(window, document);</script>
	</div>
@endsection

resources/views/product.blade.php
@extends("layouts.app")

@section("title", $product->name)

@section("meta")
	<meta property="og:url" content="{{ url()->full() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="{{ $product->name }} / {{ config('app.name') }}"/>
	<meta property="og:description" content=" {{ env("APP_DESCRIPTION") }}"/>
	<meta property="og:image" content="{{ $product->getCoverImgMin() }}"/>
	<meta property="fb:app_id" content="{{ env("FACEBOOK_APP_ID") }}">
@endsection

@section("content")
	<div class="container product-page-container">
		<div class="row product-page-box">
			<div class="col-12 col-md-8 col-lg-8">
				<div data-color="{{ $product->color()->first()->value }}" data-id="{{ $product->id }}"
				     class="left-product-box">
					<div class="image-box">
						<a data-width="760" data-fancybox="images" href="{{ $product->getCoverImg() }}">
							<img src="{{ $product->getCoverImg() }}" alt="Product image">
						</a>
					</div>
					@if($productImages->count() > 0)
						<div class="images-box mt-2">
							<div class="image-slider">
								@foreach($productImages as $image)
									<a data-fancybox="images" data-width="760"
									   href="{{ secure_asset("storage/product_images/" . $image->name) }}">
										<img src="{{ secure_asset("storage/product_images/" . $image->name) }}"
										     alt="Product image">
									</a>
								@endforeach
							</div>
						</div>
					@endif
				</div>

				@if($groupedProducts->isNotEmpty())
					<div style="overflow: hidden;" class="row grouped-products product-page-sliders d-none d-md-block">
						<div class="col-12">
							<h2>Grouped products</h2>
							<div class="group-slider grouped-products-slider slider-products">
								@foreach($groupedProducts as $groupProduct)
									<div class="product-box">
										<a href="{{ route("showProduct", ["id"=>$groupProduct->id, "slug"=>$groupProduct->slug]) }}">
											<div class="product-head">
												<img src="{{ $groupProduct->getCoverImgMin() }}" alt="product img">
											</div>
										</a>
										<div class="product-body">
											<a href="{{ route("showProduct", ["id"=>$groupProduct->id, "slug"=>$groupProduct->slug]) }}">
												<p>{{ $groupProduct->name }}</p>
											</a>
											<span>{{ $groupProduct->presentPrice() }}</span>
										</div>
									</div>
								@endforeach
							</div>
						</div>
					</div>
				@else
					<div style="overflow: hidden;"
					     class="row recommend-container product-page-sliders d-none d-md-block">
						<div class="col-12">
							<h2>Products you might like</h2>
							<div class="recommended-slider slider-products">
								<div class="product-box placeholder mr-2 float-left">
									<div class="product-head"></div>
									<div class="product-body">
										<div class="name"></div>
										<div class="price"></div>
									</div>
								</div>
								<div class="product-box placeholder mr-2 float-left">
									<div class="product-head"></div>
									<div class="product-body">
										<div class="name"></div>
										<div class="price"></div>
									</div>
								</div>
								<div class="product-box placeholder mr-2 float-left">
									<div class="product-head"></div>
									<div class="product-body">
										<div class="name"></div>
										<div class="price"></div>
									</div>
								</div>
							</div>
						</div>
					</div>

				@endif

				<div class="clearfix"></div>

				<div style="overflow: hidden;" class="row last-visited product-page-sliders d-none d-md-block">
					<div class="col-12">
						<h2>Last visited</h2>
						<div class="group-slider last-visit-slider slider-products">
							<div class="product-box placeholder mr-2 float-left">
								<div class="product-head"></div>
								<div class="product-body">
									<div class="name"></div>
									<div class="price"></div>
								</div>
							</div>
							<div class="product-box placeholder mr-2 float-left">
								<div class="product-head"></div>
								<div class="product-body">
									<div class="name"></div>
									<div class="price"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-12 col-md-4 col-lg-4">
				<div class="right-product-box layout-holder">
					@if(Auth::check() && Auth::user()->isAdmin())
						<a href="{{ route("products.edit", $product->id) }}">Edit</a>
					@endif
					<div class="essential-info">
						<h2 class="">{{ $product->name }}</h2>
						<h4 class="">{{ $product->presentPrice() }}</h4>
						<h5 class="">inc. 21% TAX</h5>
					</div>

					<div class="product-variants">
						<a class=""
						   href="{{ route("showProduct", ["id"=> $product->getMainSku()->id, "slug"=>$product->getMainSku()->slug]) }}">
							<div class="variant-box @if($product->getMainSku()->id === $product->id) active @endif">
								<img src="{{ $product->getMainSku()->getCoverImgUltraMin() }}" alt="variant photo">
							</div>
						</a>
						@foreach($product->getMainSku()->children as $child)
							<a href="{{ route("showProduct", ["id"=> $child->id, "slug"=>$child->slug]) }}">
								<div class="variant-box @if($child->id === $product->id) active @endif">
									<img src="{{ $child->getCoverImgUltraMin() }}" alt="variant photo">
								</div>
							</a>
						@endforeach
					</div>
					{{ Form::open(["url"=>route("cart.store", $product->id), "method"=>"POST", "class"=>"", "id"=>"product-form"]) }}
					<div class="row">
						<div class="col-lg-12">
							<div class="size-labels">
								@if($errors->has("size-warning"))
									<div class="inline-warning">
										{{ $errors->first("size-warning") }}
									</div>
								@endif
								@foreach($product->quantities as $quantity)
									<div class="size-label">
										@php $disabled = "" @endphp
										@if($quantity->qty <= 0)
											@php $disabled = "disabled" @endphp
										@endif
										{{ Form::radio("size", $quantity->size->id, false, ["id"=>str_slug($quantity->size->name),
										"data-qty"=>$quantity->qty,
										 "class"=>$disabled, $disabled]) }}
										{{ Form::label(str_slug($quantity->size->name), $quantity->size->name, ["class"=>$disabled . " noselect"]) }}
									</div>
								@endforeach
							</div>
						</div>
						<div class="col-lg-12">
							<div class="row">
								<div class="col-12 mt-3">
									@if($product->ratings->isNotEmpty())
										<h6 class="to-rate">{{ $ratingValue }} / 5</h6>
									@else
										<h6 class="to-rate">No ratings yet</h6>
									@endif
									@auth
										@if($displayRate)
											<div class="rating-box pt-2">
												<h6>Rate this product</h6>
												<div data-id="{{ $product->id }}"
												     class="d-flex pt-2 ratings justify-content-around">
													<div data-value="1" class="rating">1</div>
													<div data-value="2" class="rating">2</div>
													<div data-value="3" class="rating">3</div>
													<div data-value="4" class="rating">4</div>
													<div data-value="5" class="rating">5</div>
												</div>
											</div>
										@endif
									@endauth
								</div>
								<div class="col-12">
									<div class="row">
										<div class="col-7">
											<div class="qty-box">
												<div class="qty-numbers float-left ">
													<i class="fas fa-minus product-minus"></i>
												</div>
												{{ Form::number("qty", 1, ["class"=>"float-left", "readonly"]) }}
												<div class="qty-numbers float-left ">
													<i class="fas fa-plus product-plus"></i>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
										<div class="col-5">
											<div data-price="{{ $product->price }}" class="total-price text-right">
												{{ $product->presentPrice() }}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-12 mt-4">
							<div class="shopping-box">
								<div class="row">
									<div class="col-10 col-md-8">
										<button @if(!$product->hasQuantities()) disabled @endif id="add_to_basket"
										        type="submit"
										        class="btn btn-dark btn-wave p-2 d-block w-100 @if(!$product->hasQuantities()) disabled @endif">
											Add to cart
										</button>
									</div>
									<div class="col-2 col-md-4">
										<a class="add-to-favorites text-dark d-block mx-auto" data-productid="{{ $product->id }}"
										   href="{{ route("products.addToFavorites") }}">
											@auth
												@if(Auth::user()->isProductFavorite($product->id))
													<i class="fas fa-heart"></i>
												@else
													<i class="far fa-heart"></i>
												@endif
											@else
												<i class="far fa-heart"></i>
											@endauth
										</a>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-12 mt-4">
							<div class="product-information">
								{!! $product->text !!}
							</div>
						</div>
					</div>
					{{ Form::close() }}
				</div>
			</div>

			@if($groupedProducts->isNotEmpty())
				<div class="col-12">
					<div style="overflow: hidden;" class="row grouped-products product-page-sliders d-block d-md-none">
						<div class="col-12">
							<h2>Grouped products</h2>
							<div class="group-slider grouped-products-slider slider-products">
								@foreach($groupedProducts as $groupProduct)
									<div class="product-box">
										<a href="{{ route("showProduct", ["id"=>$groupProduct->id, "slug"=>$groupProduct->slug]) }}">
											<div class="product-head">
												<img src="{{ $groupProduct->getCoverImgMin() }}" alt="product img">
											</div>
										</a>
										<div class="product-body">
											<a href="{{ route("showProduct", ["id"=>$groupProduct->id, "slug"=>$groupProduct->slug]) }}">
												<p>{{ $groupProduct->name }}</p>
											</a>
											<span>{{ $groupProduct->presentPrice() }}</span>
										</div>
									</div>
								@endforeach
							</div>
						</div>
					</div>
				</div>
			@else
				<div class="col-12">
					<div style="overflow: hidden;"
					     class="row recommend-container product-page-sliders d-block d-md-none">
						<div class="col-12">
							<h2>Products you might like</h2>
							<div class="recommended-slider slider-products">
								<div class="product-box placeholder mr-2 float-left">
									<div class="product-head"></div>
									<div class="product-body">
										<div class="name"></div>
										<div class="price"></div>
									</div>
								</div>
								<div class="product-box placeholder mr-2 float-left">
									<div class="product-head"></div>
									<div class="product-body">
										<div class="name"></div>
										<div class="price"></div>
									</div>
								</div>
								<div class="product-box placeholder mr-2 float-left">
									<div class="product-head"></div>
									<div class="product-body">
										<div class="name"></div>
										<div class="price"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			@endif

			<div class="col-12">
				<div style="overflow: hidden;" class="row last-visited product-page-sliders d-block d-md-none">
					<div class="col-12">
						<h2>Last visited</h2>
						<div class="group-slider last-visit-slider slider-products">
							<div class="product-box placeholder mr-2 float-left">
								<div class="product-head"></div>
								<div class="product-body">
									<div class="name"></div>
									<div class="price"></div>
								</div>
							</div>
							<div class="product-box placeholder mr-2 float-left">
								<div class="product-head"></div>
								<div class="product-body">
									<div class="name"></div>
									<div class="price"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
@endsection

@section("additionalScripts")
	<!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>-->
@endsection

resources/views/products.blade.php
@extends("layouts.app")

@section("title", $collection->name)

@section("content")
	<div style="background-image: url({{ $collection->getCoverImg() }})" class="collection-bg">
		<div class="bg-darken"></div>
		<h2 class="text-center text-white">{{ $collection->name }}</h2>
	</div>
	<div class="section section-products">
		<div class="container">
			<div class="row">
				@if($products->count() > 0)
					<div class="col-12">
						<div class="min-filter">
							<div class="row">
								<div class="col-5 col-xs-3 col-md-4 col-xl-2">
									{{ Form::open([
									"url"=>route("products.filter"),
									"method"=>"get",
									"data-slug" => $collection->slug,
									"data-call" => route("products.filterCollections")
									])
									}}
									{{ Form::select("filter", $select, Input::get("sort"), ["class"=>"products-filter"]) }}
									{{ Form::close() }}
								</div>
							</div>
						</div>
					</div>
					<div class="col-12">
						<div class="row render-category-products">
							@foreach($products as $product)
								<div class="col-6 col-sm-4 col-md-3">
									<div class="product-box">
										<div class="product-head">
											<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}"><img
														src="{{ $product->getCoverImgMin() }}" alt="Product image"></a>
										</div>
										<div class="product-body">
											<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}">
												<p>{{ $product->name }}</p></a>
											<span>{{ $product->presentPrice() }} DOLLARS</span>
										</div>
									</div>
								</div>
							@endforeach
						</div>
					</div>
				@else
					<p class="text-center">No products :(</p>
				@endif
			</div>
		</div>
	</div>

@endsection

resources/views/productsFilter.blade.php
@extends("layouts.app")

@section("content")
	<div class="section section-products">
		<div class="container">
			@if($products->count() > 0)
				<div class="row">
					<div class="col-12">
						<div class="min-filter">
							<div class="row">
								<div class="col-5 col-xs-3 col-md-4 col-xl-2">
									{{ Form::open([
									"url"=>route("products.filterSearch"),
									"method"=>"get",
									"data-slug"=> Input::get("q"),
									"data-call" => route("products.filterSearch")
									])
									}}
									{{ Form::select("filter", $select, Input::get("sort"), ["class"=>"products-filter"]) }}
									{{ Form::close() }}
								</div>
							</div>
						</div>
					</div>
					<div class="col-12">
						<div class="row render-category-products">
							@foreach($products as $product)
								<div class="col-6 col-sm-4 col-md-3">
									<div class="product-box">
										<div class="product-head">
											<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}"><img
														src="{{ $product->getCoverImgMin() }}" alt="Product image"></a>
										</div>
										<div class="product-body">
											<a href="{{ route("showProduct", ["id"=>$product->id, "slug"=>$product->slug]) }}">
												<p>{{ $product->name }}</p></a>
											<span>{{ $product->presentPrice() }} DOLLARS</span>
										</div>
									</div>
								</div>
							@endforeach
						</div>
					</div>
					<div class="products-pagination">
						{{ $products->links() }}
					</div>
				</div>
			@else
				<p class="text-center">No products :(</p>
			@endif
		</div>
	</div>
@endsection