routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get("/KC-admin/2ýžhs7429sj28sjsaí2", "SystemController@migrate")->name("migrate");
Route::get("/KC-admin/7aUaoe0pyAsds29apa", "SystemController@rollback")->name("rollback");
Route::get("/privacypolicy", "SystemController@privacypolicy")->name("privacypolicy");

//FRONT END
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::get("/product/{id}/{slug?}", "ProductsController@show")->name("showProduct");

//Cart stuff
Route::get("/cart", "CartController@index")->name("cart.index");
Route::post("/cart/{id}", "CartController@store")->name("cart.store");
Route::delete("/cart/{product}", "CartController@destroy")->name("cart.destroy");
Route::post("/cart/update/chngqty", "CartController@update")->name("cart.changeqty");
Route::post("/cart/update/chngsize", "CartController@updateSize")->name("cart.changesize");

//USER INTERFACE
Route::get("/user/settings", "UsersController@index")->name("users.index");
Route::put("/user/settings/{id}", "UsersController@update")->name("users.update");
Route::get("/user/settings/changeavatardefault/{id}", "UsersController@changeToDefault")->name("users.changeToDefault");
Route::get("/user/settings/password", "UsersController@pass")->name("users.pass");
Route::put("/user/settings/password/{id}", "UsersController@updatePass")->name("users.updatePass");
Route::get("/user/settings/shipping", "UsersController@shipping")->name("users.shipping");
Route::put("/user/settings/shipping/{id}", "UsersController@updateShipping")->name("users.updateShipping");
Route::post("/user/settings/shipping/{id}", "UsersController@storeShipping")->name("users.storeShipping");
Route::get("/user/orders", "UsersController@orders")->name("users.orders");
Route::get("/user/orders/{id}/faktura", "OrdersController@invoice")->name("orders.invoice");
Route::delete("/user/orders/{id}/delete", "OrdersController@order")->name("orders.delete");

//PAYMENTS
Route::post("/create-payment", "PaymentController@create");
Route::post("/execute-payment", "PaymentController@execute");
Route::post("/paymentsuccess", "PaymentController@success");
Route::get("/thankyou", "PaymentController@thankyou")->name("thankyou");

//Checkout stuff
Route::get("/checkout", "CheckoutController@index")->name("checkout.index");
Route::post("/checkout", "CheckoutController@store")->name("checkout.store");


//API AJAX CALLS
Route::get("/getcart", "ProductsController@getCart");

//Products by collection
Route::get("/collections/{slug}", "CollectionsController@show")->name("showCollection");
Route::post("/collectionclick", "CollectionsController@click")->name("collectionclick");

Route::get("/categories/{slug}", "SectionsController@show")->name("homesections.show");

//Search for products
Route::get("/search", "ProductsController@search")->name("searchProducts");
Route::get("/searchfilter", "ProductsController@filter")->name("products.filterSearch");
Route::get("/clearsearch", "ProductsController@emptySearch")->name("products.clearSearch");
Route::post("/rate", "ProductsController@rate");


//BACK END
Route::get("/KC-admin", "AdminController@index")->name("admin.index");
Route::get("/KC-admin/dashboard", "AdminController@index")->name("admin.index");
Route::get("/KC-admin/login", "AdminController@login")->name("admin.login");

// Admin users
Route::get("/KC-admin/user/customers", "AdminUsersController@customers")->name("admin.users.clients");
Route::get("/KC-admin/user/employees", "AdminUsersController@employees")->name("admin.users.employees");
Route::get("/KC-admin/user/users", "AdminUsersController@users")->name("admin.users.user");
//User edit page in admin
Route::get("/KC-admin/user/{id}/edit", "AdminUsersController@edit")->name("admin.users.edit");
Route::put("/KC-admin/user/{id}", "AdminUsersController@update")->name("admin.users.update");
Route::delete("/KC-admin/user/{id}", "AdminUsersController@destroy")->name("admin.users.destroy");

Route::get("/KC-admin/orders", "AdminOrdersController@index")->name("admin.orders.index");
Route::get("/KC-admin/orders/{id}", "AdminOrdersController@edit")->name("admin.orders.edit");
Route::put("/KC-admin/orders/{id}", "AdminOrdersController@update")->name("admin.orders.update");
Route::put("/KC-admin/orders/{id}/products", "AdminOrdersController@updateProducts")->name("admin.orders.updateProducts");
Route::get("/KC-admin/orders/{id}/finish", "AdminOrdersController@finish")->name("admin.orders.finish");
Route::delete("/KC-admin/orders/{id}", "AdminOrdersController@destroy")->name("admin.orders.destroy");

// Admin products
Route::delete("/KC-admin/products/destroyImages", "AdminProductsController@destroyMultipleImages");
Route::delete("/KC-admin/products/destroyImg/image/{id}", "AdminProductsController@destroyImg")
	->name("destroyImg");
Route::resource("/KC-admin/products", "AdminProductsController", [
	"except" => "show"
]);

//API AJAX CALLS
Route::post("/addtofavorites", "ProductsController@addProductToFavorites")->name("products.addToFavorites");
Route::get("/loadmoreproducts/{offset}", "HomeController@loadmoreproducts");
Route::get("/getfavorites", "ProductsController@getFavorites");
Route::get("/getlastvisited", "ProductsController@getLastVisited");
Route::post("/addtorecommended", "ProductsController@addToRecommended");
Route::get("/getrecommendedproducts", "ProductsController@getRecommended");

//AJAX Search
Route::get("/ajax-search", "ProductsController@ajaxsearch");
Route::get("/filter-products", "SectionsController@filter")->name("products.filter");
Route::get("/filter-collection-products", "CollectionsController@filter")->name("products.filterCollections");

//Update formuláře
Route::put("/KC-admin/products/{id}/updateTags", "AdminProductsController@updateTags")->name("products.updateTags");
Route::put("/KC-admin/products/{id}/updatePhotos", "AdminProductsController@updatePhotos")->name("products.updatePhotos");
Route::put("/KC-admin/products/{id}/updateQuantities", "AdminProductsController@updateQuantities")->name("products.updateQuantities");
Route::put("/KC-admin/products/{id}/updateColors", "AdminProductsController@updateColors")->name("products.updateColors");
Route::post("/KC-admin/products/storeSku", "AdminProductsController@storeSku")->name("products.storeSku");

Route::post("/KC-admin/products/ajax-upload/{productId}", "AdminProductsController@ajaxImgUpload")
	->name("product-ajax-upload");
Route::post("/KC-admin/products/uploadMoreImages", "AdminProductsController@uploadMultipleImages")
	->name("uploadMoreImages");
Route::post("/KC-admin/products/updateImgPosition", "AdminProductsController@updatePhotosPosition");
Route::post("/KC-admin/products/updateSlidesPosition", "AdminSlidersController@updateSlidesPosition");


// Admin sliders
Route::resource("/KC-admin/sliders", "AdminSlidersController", [
	"except" => "show"
]);
Route::post("/click", "SlidersController@click");
Route::put("/KC-admin/sliders/{id}/changeActive", "AdminSlidersController@changeActive")->name("sliders.changeActive");

// Admin collections
Route::resource("/KC-admin/collections", "AdminCollectionsController", [
	"except" => "show"
]);

// Admin sections
Route::resource("/KC-admin/sections", "AdminSectionsController");

// Admin tags
Route::resource("/KC-admin/tags", "AdminTagsController", [
	"except" => "show"
]);

Route::get('adminauth/google', 'SocialAuthController@redirectToAdminProvider');

Route::get('auth/{provider}', 'SocialAuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'SocialAuthController@handleProviderCallback');

resources/views/inc/adminflashes.blade.php
@if(count($errors) > 0)
	<div class="row">
		<div class="col-12 pb-3">
			<div class="alert alert-danger alert-dismissible fade show" role="alert">
				<strong>Ooops...</strong>
				@foreach($errors->all() as $error)
					<p>{{$error}}</p>
				@endforeach
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
@endif


@if (session('status'))
	<div class="row">
		<div class="col-12 pb-3">
			<div class="alert alert-info alert-dismissible fade show" role="alert">
				<strong>Status</strong>
				<p>{{session("status")}}</p>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
@endif

@if(session("success"))
	<div class="row">
		<div class="col-12 pb-3">
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<strong>Hurray!</strong>
				<p>{{session("success")}}</p>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
@endif

@if(session("error"))
	<div class="row">
		<div class="col-12 pb-3">
			<div class="alert alert-danger alert-dismissible fade show" role="alert">
				<strong>Oops...</strong>
				<p>{{session("error")}}</p>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
@endif

resources/views/inc/adminnavbar.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-kira">
	<a class="navbar-brand admin pr-3" href="{{ route("admin.index") }}">
		Kira Admin
	</a>
	<p class="mb-0"><a target="_blank" href="{{ route("home") }}">Home</a></p>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
	        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto d-block d-md-none">
			<li class="nav-item">
				<a class="nav-link" href="{{ route("products.index") }}">Products</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
				   aria-haspopup="true" aria-expanded="false">
					Products dropdown
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{{ route("products.index") }}">Products</a>
					<a class="dropdown-item" href="{{ route("products.create") }}">Add a product</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{{ route("sections.index") }}">Categories</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{{ route("tags.index") }}">Tags</a>
				</div>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ route("sliders.index") }}">Slider</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ route("collections.index") }}">Collections</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown"
				   aria-haspopup="true" aria-expanded="false">
					Users dropdown
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown1">
					<a class="dropdown-item" href="{{ route("admin.users.clients") }}">Customers</a>
					<a class="dropdown-item" href="{{ route("admin.users.employees") }}">Employees</a>
					<a class="dropdown-item" href="{{ route("admin.users.user") }}">Users</a>
				</div>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ route("collections.index") }}">Orders</a>
			</li>
		</ul>
	</div>
</nav>

<div class="leftnav">
	<div class="profile text-left">
		<div class="adminuser-wrapper p-3">
			<div class="row">
				<div class="col-2">
					<div class="ui avatar">
						<img class="image" src="{{ Auth::user()->getAvatar() }}">
					</div>
				</div>
				<div class="col-10">
					<span class="d-inline-block medium">{{ Auth::user()->name }}</span>
					<div class="clearfix"></div>
					<small class="mt-2 d-inline-block">{{ Auth::user()->role }}</small>
					<small class="d-inline-block px-1"> |</small>
					<small class="mt-2 d-inline-block text-primary">
						<a class="text-danger" href="{{ route('logout') }}"
						   onclick="event.preventDefault();document.getElementById('logout-form').submit();">{{ __('logout') }}</a>
					</small>
					<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
						@csrf
					</form>
					@if(Auth::user()->isSuperAdmin())
						<small><a onclick="return confirm('You are about to migrate the database. Are you sure?')"
						          href="{{ route("migrate") }}">migrate</a></small>
						<small class="d-inline-block px-1"> |</small>
						<small><a onclick="return confirm('You are about to rollback the database. Are you sure?')"
						          class="text-danger" href={{ route("rollback") }}>rollback</a></small>
					@endif
				</div>
			</div>
		</div>

		<ul class="admin-abilities mb-3">
			<div class="btn-group dropright btn-block">
				<button type="button"
				        class="btn btn-light btn-block btn-wave
@if(Request::is('KC-admin/products*') || Request::is('KC-admin/sections*') || Request::is('KC-admin/tags*')) active @endif"
				        @if(!Request::is('KC-admin/products*') && !Request::is('KC-admin/sections*') && !Request::is('KC-admin/tags*')) data-additional-styles="dark" @endif>
					<a href="{{ route("products.index") }}">
						<i class="fas fa-box-open"></i> Products
					</a>
				</button>
				<button type="button"
				        class="btn btn-light dropdown-toggle dropdown-toggle-split @if(Request::is('KC-admin/products*')
				         || Request::is('KC-admin/sections*')
				         || Request::is("KC-admin/tags*")) active @endif"
				        data-toggle="dropdown"
				        aria-haspopup="true" aria-expanded="false">
					<span class="sr-only">Toggle Dropright</span>
				</button>
				<div class="dropdown-menu">
					<h6 class="ml-3 mt-3 bold">Products</h6>
					<a href="{{ route("products.index") }}" class="dropdown-item a-wave">
						<i class="fas fa-list-ol mr-2"></i>
						Products
					</a>
					<a href="{{ route("products.create") }}" class="dropdown-item a-wave">
						<i class="fas fa-plus mr-2"></i>
						Add a product
					</a>
					<div class="dropdown-divider"></div>
					<h6 class="ml-3 mt-3 bold">Categories</h6>
					<a href="{{ route("sections.index") }}" class="dropdown-item a-wave">
						<i class="fas fa-list-ol mr-2"></i>
						Categories
					</a>
					<div class="dropdown-divider"></div>
					<h6 class="ml-3 mt-3 bold">Tags</h6>
					<a href="{{ route("tags.index") }}" class="dropdown-item a-wave">
						<i class="fas fa-list-ol mr-2"></i>
						Tags
					</a>
				</div>
			</div>
			@if(Request::is('KC-admin/products*') || Request::is('KC-admin/sections*') || Request::is("KC-admin/tags*"))
				<ul class="admin-leftsubbar">
					<li>
						<a href="{{ route("products.index") }}">
							Products
						</a>
					</li>
					<li>
						<a href="{{ route("products.create") }}">
							Add a product
						</a>
					</li>
					<li>
						<a href="{{ route("sections.index") }}">
							Categories
						</a>
					</li>
					<li>
						<a href="{{ route("tags.index") }}">
							Tags
						</a>
					</li>
				</ul>
			@endif

			<div class="btn-group dropright btn-block">
				<button type="button"
				        class="btn btn-light btn-block btn-wave @if(Request::is('KC-admin/sliders*')) active @endif"
				        @if(!Request::is('KC-admin/sliders*')) data-additional-styles="dark" @endif>
					<a href="{{ route("sliders.index") }}">
						<i class="fas fa-ad"></i> Slider
					</a>
				</button>
				<button type="button"
				        class="btn btn-light dropdown-toggle
				        dropdown-toggle-split @if(Request::is('KC-admin/sliders*')) active @endif"
				        data-toggle="dropdown"
				        aria-haspopup="true" aria-expanded="false">
					<span class="sr-only">Toggle Dropright</span>
				</button>
				<div class="dropdown-menu">
					<a href="{{ route("sliders.index") }}" class="dropdown-item a-wave">
						<i class="fas fa-list-ol mr-2"></i>
						Slides
					</a>
					<a href="{{ route("sliders.create") }}" class="dropdown-item a-wave">
						<i class="fas fa-plus mr-2"></i>
						Add a slide
					</a>
				</div>
			</div>
			@if(Request::is('KC-admin/sliders*'))
				<ul class="admin-leftsubbar">
					<li>
						<a href="{{ route("sliders.index") }}">
							Slides
						</a>
					</li>
					<li>
						<a href="{{ route("sliders.create") }}">
							Add a slide
						</a>
					</li>

				</ul>
			@endif

			<div class="btn-group dropright btn-block">
				<button type="button"
				        class="btn btn-light btn-block btn-wave @if(Request::is('KC-admin/collections*')) active @endif"
				        @if(!Request::is('KC-admin/collections*')) data-additional-styles="dark" @endif>
					<a href="{{ route("collections.index") }}">
						<i class="fas fa-camera-retro"></i> Collections
					</a>
				</button>
				<button type="button"
				        class="btn btn-light dropdown-toggle dropdown-toggle-split @if(Request::is('KC-admin/collections*')) active @endif"
				        data-toggle="dropdown"
				        aria-haspopup="true" aria-expanded="false">
					<span class="sr-only">Toggle Dropright</span>
				</button>
				<div class="dropdown-menu">
					<a href="{{ route("collections.index") }}" class="dropdown-item a-wave">
						<i class="fas fa-list-ol mr-2"></i>
						Collections
					</a>
					<a href="{{ route("collections.create") }}" class="dropdown-item a-wave">
						<i class="fas fa-plus mr-2"></i>
						Add a collection
					</a>
				</div>
			</div>
			@if( Request::is('KC-admin/collections*'))
				<ul class="admin-leftsubbar menu">
					<li>
						<a href="{{ route("collections.index") }}">
							Collections
						</a>
					</li>
					<li>
						<a href="{{ route("collections.create") }}">
							Add a collection
						</a>
					</li>

				</ul>
			@endif

			<div class="btn-group dropright btn-block">
				<button type="button"
				        class="btn btn-light btn-block btn-wave @if(Request::is('KC-admin/user*')) active @endif"
				        @if(!Request::is('KC-admin/user*')) data-additional-styles="dark" @endif>
					<a href="{{ route("admin.users.user") }}">
						<i class="fas fa-users"></i> Users
					</a>
				</button>
				<button type="button"
				        class="btn btn-light dropdown-toggle dropdown-toggle-split @if(Request::is('KC-admin/user/*')) active @endif"
				        data-toggle="dropdown"
				        aria-haspopup="true" aria-expanded="false">
					<span class="sr-only">Toggle Dropright</span>
				</button>
				<div class="dropdown-menu">
					<a class="text-left dropdown-item a-wave" href="{{ route("admin.users.clients") }}">
						Customers
					</a>
					<a class="text-left dropdown-item a-wave" href="{{ route("admin.users.employees") }}">
						Employees
					</a>
					<a class="text-left dropdown-item a-wave" href="{{ route("admin.users.user") }}">
						Users
					</a>
				</div>
			</div>
			@if(Request::is('KC-admin/user*'))
				<ul class="admin-leftsubbar">
					<li>
						<a href="{{ route("admin.users.clients") }}">
							Customers
						</a>
					</li>
					<li>
						<a href="{{ route("admin.users.employees") }}">
							Employees
						</a>
					</li>
					<li>
						<a href="{{ route("admin.users.user") }}">
							Users
						</a>
					</li>
				</ul>
			@endif
			<li class="dropright">
				<button type="button"
				        class="btn btn-light btn-block btn-wave @if(Request::is('KC-admin/orders*')) active @endif"
				        @if(!Request::is('KC-admin/orders*')) data-additional-styles="dark" @endif>
					<a href="{{ route("admin.orders.index") }}">
						<i class="fas fa-shopping-basket"></i> Orders
					</a>
				</button>
			</li>

		</ul>
	</div>
</div>

resources/views/inc/flashes.blade.php
@if (session('status'))
	<div class="container-full alert alert-info alert-dismissible fade show" role="danger">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<strong>Status</strong>
					<p>{{session("status")}}</p>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			</div>
		</div>
	</div>
@endif

@if(session("success"))
	<div class="container-full alert alert-success alert-dismissible fade show" role="danger">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<strong>Success</strong>
					<p>{{session("success")}}</p>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			</div>
		</div>
	</div>
@endif

@if(session("error"))
	<div class="container-full alert alert-danger alert-dismissible fade show" role="danger">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<strong>Error!</strong>
					<p>{{session("error")}}</p>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			</div>
		</div>
	</div>
@endif

@if(session("warning"))
	<div class="container-full alert alert-warning alert-dismissible fade show" role="danger">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<strong>Warning</strong>
					<p>{{session("warning")}}</p>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			</div>
		</div>
	</div>
@endif

resources/views/inc/footer.blade.php
<div class="section section-footer">
	<div class="container">
		<div class="row">
			<div class="text-center text-md-left col-12 col-lg-3 col-md-4">
				<h5>Welcome to Kira Clothing!</h5>
				<p>
					This is a graduation project by <a target="_blank" href="https://www.instagram.com/tomkrcal/">Tomáš
						Krčál</a>
					made possible by using <a target="_blank" href="https://laravel.com/">Laravel</a> for back-end and
					<a href="https://getbootstrap.com/">Bootstrap 4</a> with <a target="_blank"
					                                                            href="https://jquery.com/">jQuery</a>
					for the front-end.
					On this website you can find clothing I've designed myself. Any purchase made on this server will
					not be fulfilled since
					this website is for testing purposes only
				</p>
			</div>
			<div class="offset-lg-3 offset-md-2"></div>
			<div class="text-center text-md-left col-12 col-md-2">
				<h5>Sitemap</h5>
				<ul>
					<li><a href="{{ route("home") }}">Home</a></li>
					<li><a href="{{ route("cart.index") }}">Cart</a></li>
					@auth
						<li>
							<a href="{{ route('logout') }}"
							   onclick="event.preventDefault();
                                                     document.getElementById('logout-form2').submit();">
								Log out
							</a>
							<form id="logout-form2" action="{{ route('logout') }}" method="POST" class="d-none">
								@csrf
							</form>
						</li>
					@else
						<li><a href="{{ route("login") }}">Log in</a></li>
						<li><a href="{{ route("register") }}">Register</a></li>
					@endauth
				</ul>
			</div>
			<div class="text-center text-md-left col-12 col-md-2">
				<h5>Socials</h5>
				<ul>
					<li><a href="">facebook</a></li>
					<li><a href="">instagram</a></li>
					<li><a href="">youtube</a></li>
					<li><a href="">twitter</a></li>
				</ul>
			</div>
			<div class="text-center text-md-left col-12 col-md-2">
				<h5>Business</h5>
				<ul>
					<li><a href="">Contact</a></li>
					<li><a href="{{ route("privacypolicy") }}">Privacy Policy</a></li>
					<li><a href="">Agreement to service</a></li>
				</ul>
			</div>
		</div>
		<div class="row mt-4">
			<div class="col-12">
				<p class="text-center text-dark">&copy; 2019 Tomáš Krčál - All right reserved</p>
			</div>
		</div>
	</div>
</div>

resources/views/inc/usermenu.blade.php
<ul>
	<li>
		<a class="@if(Request::is("user/settings")) active @endif"
		   href="{{ route("users.index") }}">Profile information</a>
	</li>
	<li>
		<a class="@if(Request::is("user/settings/password")) active @endif"
		   href="{{ route("users.pass") }}">Change password</a>
	</li>
	<li>
		<a class="@if(Request::is("user/settings/shipping")) active @endif"
		   href="{{ route("users.shipping") }}">Shipping address</a>
	</li>
	<li>
		<a class="@if(Request::is("user/orders")) active @endif"
		   href="{{ route("users.orders") }}">Manage orders</a>
	</li>
</ul>