routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get("/KC-admin/2ýžhs7429sj28sjsaí2", "SystemController@migrate")->name("migrate");
Route::get("/KC-admin/7aUaoe0pyAsds29apa", "SystemController@rollback")->name("rollback");
Route::get("/privacypolicy", "SystemController@privacypolicy")->name("privacypolicy");

//FRONT END
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::get("/product/{id}/{slug?}", "ProductsController@show")->name("showProduct");

//Cart stuff
Route::get("/cart", "CartController@index")->name("cart.index");
Route::post("/cart/{id}", "CartController@store")->name("cart.store");
Route::delete("/cart/{product}", "CartController@destroy")->name("cart.destroy");
Route::post("/cart/update/chngqty", "CartController@update")->name("cart.changeqty");
Route::post("/cart/update/chngsize", "CartController@updateSize")->name("cart.changesize");

//USER INTERFACE
Route::get("/user/settings", "UsersController@index")->name("users.index");
Route::put("/user/settings/{id}", "UsersController@update")->name("users.update");
Route::get("/user/settings/changeavatardefault/{id}", "UsersController@changeToDefault")->name("users.changeToDefault");
Route::get("/user/settings/password", "UsersController@pass")->name("users.pass");
Route::put("/user/settings/password/{id}", "UsersController@updatePass")->name("users.updatePass");
Route::get("/user/settings/shipping", "UsersController@shipping")->name("users.shipping");
Route::put("/user/settings/shipping/{id}", "UsersController@updateShipping")->name("users.updateShipping");
Route::post("/user/settings/shipping/{id}", "UsersController@storeShipping")->name("users.storeShipping");
Route::get("/user/orders", "UsersController@orders")->name("users.orders");
Route::get("/user/orders/{id}/faktura", "OrdersController@invoice")->name("orders.invoice");
Route::delete("/user/orders/{id}/delete", "OrdersController@order")->name("orders.delete");

//PAYMENTS
Route::post("/create-payment", "PaymentController@create");
Route::post("/execute-payment", "PaymentController@execute");
Route::post("/paymentsuccess", "PaymentController@success");
Route::get("/thankyou", "PaymentController@thankyou")->name("thankyou");

//Checkout stuff
Route::get("/checkout", "CheckoutController@index")->name("checkout.index");
Route::post("/checkout", "CheckoutController@store")->name("checkout.store");


//API AJAX CALLS
Route::get("/getcart", "ProductsController@getCart");

//Products by collection
Route::get("/collections/{slug}", "CollectionsController@show")->name("showCollection");
Route::post("/collectionclick", "CollectionsController@click")->name("collectionclick");

Route::get("/categories/{slug}", "SectionsController@show")->name("homesections.show");

//Search for products
Route::get("/search", "ProductsController@search")->name("searchProducts");
Route::get("/searchfilter", "ProductsController@filter")->name("products.filterSearch");
Route::get("/clearsearch", "ProductsController@emptySearch")->name("products.clearSearch");
Route::post("/rate", "ProductsController@rate");


//BACK END
Route::get("/KC-admin", "AdminController@index")->name("admin.index");
Route::get("/KC-admin/dashboard", "AdminController@index")->name("admin.index");
Route::get("/KC-admin/login", "AdminController@login")->name("admin.login");

// Admin users
Route::get("/KC-admin/user/customers", "AdminUsersController@customers")->name("admin.users.clients");
Route::get("/KC-admin/user/employees", "AdminUsersController@employees")->name("admin.users.employees");
Route::get("/KC-admin/user/users", "AdminUsersController@users")->name("admin.users.user");
//User edit page in admin
Route::get("/KC-admin/user/{id}/edit", "AdminUsersController@edit")->name("admin.users.edit");
Route::put("/KC-admin/user/{id}", "AdminUsersController@update")->name("admin.users.update");
Route::delete("/KC-admin/user/{id}", "AdminUsersController@destroy")->name("admin.users.destroy");

Route::get("/KC-admin/orders", "AdminOrdersController@index")->name("admin.orders.index");
Route::get("/KC-admin/orders/{id}", "AdminOrdersController@edit")->name("admin.orders.edit");
Route::put("/KC-admin/orders/{id}", "AdminOrdersController@update")->name("admin.orders.update");
Route::put("/KC-admin/orders/{id}/products", "AdminOrdersController@updateProducts")->name("admin.orders.updateProducts");
Route::get("/KC-admin/orders/{id}/finish", "AdminOrdersController@finish")->name("admin.orders.finish");
Route::delete("/KC-admin/orders/{id}", "AdminOrdersController@destroy")->name("admin.orders.destroy");

// Admin products
Route::delete("/KC-admin/products/destroyImages", "AdminProductsController@destroyMultipleImages");
Route::delete("/KC-admin/products/destroyImg/image/{id}", "AdminProductsController@destroyImg")
	->name("destroyImg");
Route::resource("/KC-admin/products", "AdminProductsController", [
	"except" => "show"
]);

//API AJAX CALLS
Route::post("/addtofavorites", "ProductsController@addProductToFavorites")->name("products.addToFavorites");
Route::get("/loadmoreproducts/{offset}", "HomeController@loadmoreproducts");
Route::get("/getfavorites", "ProductsController@getFavorites");
Route::get("/getlastvisited", "ProductsController@getLastVisited");
Route::post("/addtorecommended", "ProductsController@addToRecommended");
Route::get("/getrecommendedproducts", "ProductsController@getRecommended");

//AJAX Search
Route::get("/ajax-search", "ProductsController@ajaxsearch");
Route::get("/filter-products", "SectionsController@filter")->name("products.filter");
Route::get("/filter-collection-products", "CollectionsController@filter")->name("products.filterCollections");

//Update formuláře
Route::put("/KC-admin/products/{id}/updateTags", "AdminProductsController@updateTags")->name("products.updateTags");
Route::put("/KC-admin/products/{id}/updatePhotos", "AdminProductsController@updatePhotos")->name("products.updatePhotos");
Route::put("/KC-admin/products/{id}/updateQuantities", "AdminProductsController@updateQuantities")->name("products.updateQuantities");
Route::put("/KC-admin/products/{id}/updateColors", "AdminProductsController@updateColors")->name("products.updateColors");
Route::post("/KC-admin/products/storeSku", "AdminProductsController@storeSku")->name("products.storeSku");

Route::post("/KC-admin/products/ajax-upload/{productId}", "AdminProductsController@ajaxImgUpload")
	->name("product-ajax-upload");
Route::post("/KC-admin/products/uploadMoreImages", "AdminProductsController@uploadMultipleImages")
	->name("uploadMoreImages");
Route::post("/KC-admin/products/updateImgPosition", "AdminProductsController@updatePhotosPosition");
Route::post("/KC-admin/products/updateSlidesPosition", "AdminSlidersController@updateSlidesPosition");


// Admin sliders
Route::resource("/KC-admin/sliders", "AdminSlidersController", [
	"except" => "show"
]);
Route::post("/click", "SlidersController@click");
Route::put("/KC-admin/sliders/{id}/changeActive", "AdminSlidersController@changeActive")->name("sliders.changeActive");

// Admin collections
Route::resource("/KC-admin/collections", "AdminCollectionsController", [
	"except" => "show"
]);

// Admin sections
Route::resource("/KC-admin/sections", "AdminSectionsController");

// Admin tags
Route::resource("/KC-admin/tags", "AdminTagsController", [
	"except" => "show"
]);

Route::get('adminauth/google', 'SocialAuthController@redirectToAdminProvider');

Route::get('auth/{provider}', 'SocialAuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'SocialAuthController@handleProviderCallback');

app/Http/Controllers/SlidersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Slide;

class SlidersController extends Controller
{

	/**
	 * @param Request $request
	 * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
	 */
	public function click(Request $request)
	{
		if ($request->ajax()) {
			$slider = Slide::findOrFail($request->input("id"));
			$slider->addClick();

			return response()->json([
				"message"=>"succes"
			]);
		}
		return back();
	}

}

resources/views/admin/sliders/create.blade.php
@extends("layouts.admin")

@section("title", "Create new slide")

@section("content")

	<div class="col-lg-8">
		<div class="admin-block">
			<div class="admin-header">
				<h3 class="">Create new slide</h3>
			</div>
			<div class="admin-body">
				{{ Form::open(["url"=>route("sliders.store"),"class"=>"" ,"method"=>"post","enctype"=>"multipart/form-data"]) }}
				<div class="form-group row">
					{{ Form::label("slider_header", "Slider heading", ["class"=>"col-sm-3 col-form-label text-md-left required"]) }}
					<div class="col-sm-8 ">
						{{ Form::text("slider_header", "", ["class"=>"form-control"]) }}
					</div>
				</div>
				<div class="form-group row">
					{{ Form::label("slider_text", "Slider text", ["class"=>"col-sm-3 col-form-label text-md-left required"]) }}
					<div class="col-sm-8 ">
						{{ Form::text("slider_text", "", ["class"=>"form-control"]) }}
					</div>
				</div>
				<div class="form-group row">
					{{ Form::label("slider_image", "Slide cover photo", ["class"=>"col-sm-3 col-form-label  text-md-left required"]) }}
					<div class="col-8 ">
						<div class="custom-file">
							{{ Form::file("slider_image", ["class"=>"custom-file-input form-control-file"]) }}
							{{ Form::label("slider_image", "Choose a file...", ["class"=>"custom-file-label"]) }}
						</div>
					</div>
				</div>
				<div class="form-group row">
					{{ Form::label("slider_link", "Destination link", ["class"=>"col-sm-3 col-form-label text-md-left "]) }}
					<div class="col-sm-8 ">

						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text">{{ url("/") }}</span>
							</div>
							{{ Form::text("slider_link", "", ["class"=>"form-control"]) }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-11">
						{{ Form::submit("Add slider",["class"=>"btn btn-primary ml-auto d-block"]) }}
					</div>
				</div>
				{{ Form::close() }}
			</div>
		</div>
	</div>

@endsection

resources/views/admin/sliders/edit.blade.php
@extends("layouts.admin")

@section("content")

	<div class="col-8">
		<div class="admin-block">
			<div class="admin-header">
				<h3 class="">Edit slide: {{ $slide->heading }}</h3>
			</div>
			<div class="admin-body">
				{{ Form::open(["url"=>route("sliders.update", $slide->id), "class"=>"", "method"=>"PUT", "enctype"=>"multipart/form-data"]) }}
				<div class="form-group row">
					{{ Form::label("slider_header", "Slider heading", ["class"=>"col-sm-3 col-form-label text-md-left "]) }}
					<div class="col-sm-8 ">
						{{ Form::text("slider_header", $slide->heading, ["class"=>"form-control"]) }}
					</div>
				</div>
				<div class="form-group row">
					{{ Form::label("slider_text", "Slider text", ["class"=>"col-sm-3 col-form-label text-md-left "]) }}
					<div class="col-sm-8 ">
						{{ Form::text("slider_text", $slide->text, ["class"=>"form-control"]) }}
					</div>
				</div>
				<div class="form-group row">
					{{ Form::label("slider_image", "Slide cover photo", ["class"=>"col-sm-3 col-form-label  text-md-left"]) }}
					<div class="col-8 ">
						<div class="custom-file">
							{{ Form::file("slider_image", ["class"=>"custom-file-input form-control-file"]) }}
							{{ Form::label("slider_image", "Choose a file...", ["class"=>"custom-file-label"]) }}
						</div>
					</div>
				</div>
				<div class="form-group row">
					{{ Form::label("slider_link", "Destination link", ["class"=>"col-sm-3 col-form-label text-md-left "]) }}
					<div class="col-sm-8 ">
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text">{{ url("/") }}</span>
							</div>
							{{ Form::text("slider_link", $slide->url_dest, ["class"=>"form-control"]) }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-11">
						{{ Form::submit("Update slider",["class"=>"btn btn-primary ml-auto d-block"]) }}
					</div>
				</div>

				{{ Form::close() }}
			</div>
		</div>
	</div>

@endsection

resources/views/admin/sliders/index.blade.php
@extends('layouts.admin')

@section("title", "Slider")

@section('content')
	<div class="col-lg-8 col-12">
		<div class="admin-block">
			<div class="admin-header">
				<h3 class=" float-left">Slider</h3>
				<a class="float-right" href="{{ route("sliders.create") }}">
					<button type="button" class="btn-primary d-block btn-wave btn">
						Add new
						<i class="fas ml-2 fa-plus"></i>
					</button>
				</a>
				<div class="clearfix"></div>
			</div>
			<div class="admin-body">
				@if(count($slides) > 0)
					<table class="table stackable ui col-12 sortable">
						<thead>
						<tr>
							<th><a data-sortable="id" href="{{ url()->current() }}">ID</a></th>
							<th><a data-sortable="heading" href="{{ url()->current() }}">Heading</a></th>
							<th><a data-sortable="text" href="{{ url()->current() }}">Text</a></th>
							<th><a data-sortable="clicks" href="{{ url()->current() }}">Clicks</a></th>
							<th></th>
							<th></th>
							<th></th>
						</tr>
						</thead>
						<tbody>
						@foreach($slides as $slide)
							<tr>
								<td>{{ $slide->id }}</td>
								<td>{{ $slide->heading }}</td>
								<td>{{ $slide->text }}</td>
								<td>{{ $slide->clicks}}</td>
								<td>
									{{ Form::open(["url"=>route("sliders.changeActive", $slide->id), "method"=>"put"]) }}
									<button type="submit" style="background:none;border:none;" role="button"
									        class="@if($slide->isActive()) ? text-secondary : text-success @endif">
										Active
									</button>
									{{ Form::close() }}
								</td>
								<td><a href="{{ route("sliders.edit", $slide->id) }}">Edit</a></td>
								<td>
									{{ Form::open(["url"=>route("sliders.destroy", $slide->id), "method"=>"delete","enctype"=>"multipart/form-data"]) }}
									<button onclick="return confirm('Are you sure?')"
									        style="background:none;border:none;"
									        type="submit" role="text"><a class="text-danger">Delete</a></button>
									{{ Form::close() }}
								</td>
							</tr>
						@endforeach
						</tbody>
					</table>
				@endif
			</div>
		</div>
	</div>
	<div class="col-4">
		<div class="admin-block">
			<div class="admin-header">
				<h3>Active slides</h3>
			</div>
			<div class="admin-body">
				<div class="slides">
					@foreach($activeSlides as $activeSlide)
						<div data-id="{{ $activeSlide->id }}"
						     class="slide d-flex align-items-center justify-content-center"
						     style="background-image: url({{ $activeSlide->getCoverImg() }})">
							<p class="text-white">{{ $activeSlide->heading }}</p>
						</div>
					@endforeach
				</div>
			</div>
		</div>
	</div>
	<div class="col-12">
		<div class="admin-block">
		</div>
	</div>
@endsection